import { Inter } from "next/font/google";
import "./globals.css";
import "../../../public/bootstrap/css/bootstrap.min.css";
import "../../../public/bootstrap/css/style.css";
import "../../../public/bootstrap/css/danhmuc.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Providers from "@/redux/provider"; // Ensure this path is correct

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}
